" get pathogen working
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

set nocompatible

set ruler " line numbers
set hidden

" settings needed for solarized colorscheme
syntax enable
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
" / solarized settings

" set up spellcheck but turn it off by default
if version >= 700
   set spl=en spell
   set nospell
endif

" only load the closetag plugin for HTML and XML files
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim

" set the default font
set guifont=Monaco:h13

" tabbing and shifting etc
set tabstop=2
set expandtab
"tab key style paragraph indent
set shiftwidth=2

"line numbers
set number

" location of ctags files
let Tlist_Ctags_Cmd='/usr/local/bin/ctags' 
" omnicompletion
set ofu=syntaxcomplete#Complete

" not sure exactly what these do
set ignorecase
set smartcase

"smart indenting
set smartindent
set autoindent

" Autocompletion stuff
set wildmenu
set wildmode=list:longest,full

" remove the buffer when I close a tab
set nohidden

" map jj to esc in insert mode
inoremap jj <Esc>

set laststatus=2
"higher linespacing than default
set linespace=3
"move new split pane to bottom
set splitbelow
"split pane to RHS
set splitright
"highlight mstching search 
set hlsearch
"allow code folding. shortcuts: zc zo
set foldenable
"needed so NERDcommenter knows what file it's dealing with
filetype plugin on
"not sure
filetype indent on
"map :NERDTreeToggle to Ctrl-D
nmap <silent> <C-D> :NERDTreeToggle<CR>
"change zen coding expander shortcut
let g:user_zen_expandabbr_key = '<C-e>'

" Instruction for how to turn on indent guides
" Press leader key (\ by default) then type 'ig'

"source the .vimrc automatically after saving it
if has("autocmd")
  autocmd bufwritepost .vimrc source $MYVIMRC
endif

" Create Blank Newlines and stay in Normal mode
nnoremap <silent> zj o<Esc>
nnoremap <silent> zk O<Esc>

" Space will toggle folds!
nnoremap <space> za

" Search mappings: These will make it so that going to the next one in a
" search will center on the line it's found in.
map N Nzz
map n nzz

if has("autocmd")
  " Highlight TODO, FIXME, NOTE, etc.
  if v:version > 701
    autocmd Syntax * call matchadd('Todo',  '\W\zs\(TODO\|FIXME\|CHANGED\|XXX\|BUG\|HACK\)')
    autocmd Syntax * call matchadd('Debug', '\W\zs\(NOTE\|INFO\|IDEA\)')
  endif
endif

"create an abbreviation for insert mode
"iabbrev abbreviation expansion
"create an abbreviation for normal mode
"abbrev abbreviation expansion
"nmap -> normal mode keymap
"imap -> insert mode keymap
